### ISSUE TITLE
There should be huaji elements in huaji filesystem.

### ISSUE THREAD

**Issue by AlaricGilbert** [luojia65/huaji-fs#1]
There should be **huaji** elements in **huaji** filesystem.(huaji)

**Comment by luojia65** [comment]
Huaji. Add in next version

**Comment by AlaricGilbert** [comment]
have u added huaji element?![1](https://user-images.githubusercontent.com/36405110/53387307-3f00d000-39c1-11e9-91c8-e319161bb8ae.jpg)

**Comment by luojia65** [comment]
After this commit https://github.com/luojia65/huaji-fs/commit/c590f2ab0c19cb990efd2f43384fbcd3bef136ac, you are able to use `huaji` command that prints a *huaji* when executed.
